import time
import pytest
from pageobjects.HomePage import HomePage
from pageobjects.FindAnAgentPage import FindAnAgent


@pytest.mark.usefixtures("set_up")
class TestRent:

    def test_one(self):
        rent_tab=HomePage(self.driver)
        rent_tab.click_rent_tab()
        time.sleep(2)
        rent_tab.click_owner_properties()
        time.sleep(2)
        rent_tab.switch_tab()
        time.sleep(2)
        rent_tab.click_top_localities()
        time.sleep(2)
        rent_tab.click_pune_mumbai_it_corridor()
        time.sleep(5)
        rent_tab.click_done()
        time.sleep(3)
        rent_tab.select_property()
        time.sleep(3)
        rent_tab.switch_tab()
        time.sleep(3)
        rent_tab.enter_your_name()
        time.sleep(6)
        rent_tab.enter_your_email()
        time.sleep(3)
        rent_tab.enter_you_number()
        time.sleep(5)

    def test_two(self):
        rent_tab = HomePage(self.driver)
        rent_tab.click_rent_tab()
        time.sleep(2)
        rent_tab.select_location_bar()
        time.sleep(2)
        rent_tab.select_location()
        time.sleep(2)
        rent_tab.click_rent_bar()
        time.sleep(2)
        rent_tab.click_search()
        time.sleep(5)

    def test_three(self):
        rent_tab = HomePage(self.driver)
        rent_tab.click_rent_tab()
        time.sleep(2)
        rent_tab.select_location_bar()
        time.sleep(2)
        rent_tab.select_location()
        time.sleep(2)
        rent_tab.click_rent_bar()
        time.sleep(2)
        rent_tab.click_search()
        time.sleep(2)
        rent_tab.click_top_agents()
        time.sleep(5)

    def test_four(self):
        rent_tab = HomePage(self.driver)
        find_agent = FindAnAgent(self.driver)
        rent_tab.click_rent_tab()
        time.sleep(2)
        rent_tab.click_find_an_agent()
        time.sleep(2)
        rent_tab.switch_tab()
        time.sleep(2)
        find_agent.click_rent_tab()
        time.sleep(2)
        find_agent.click_ask_a_question()
        time.sleep(5)

    def test_five(self):
        rent_tab = HomePage(self.driver)
        find_agent = FindAnAgent(self.driver)
        rent_tab.click_rent_tab()
        time.sleep(2)
        rent_tab.click_find_an_agent()
        time.sleep(2)
        rent_tab.switch_tab()
        time.sleep(2)
        find_agent.click_rent_tab()
        time.sleep(2)
        find_agent.click_set_a_property_alert()
        time.sleep(2)
        find_agent.click_rent_radio_button()
        time.sleep(2)
        find_agent.select_property_type()
        time.sleep(2)
        find_agent.click_hostel()
        find_agent.click_s()
        time.sleep(2)
        find_agent.select_budget_list()
        time.sleep(2)
        find_agent.click_10k_to_15k()
        find_agent.click_s()
        time.sleep(2)
        find_agent.select_bed_room()
        time.sleep(2)
        find_agent.click_two()
        find_agent.click_s()
        time.sleep(2)
        find_agent.select_floor_preference()
        time.sleep(2)
        find_agent.click_10th_floor_and_above()
        find_agent.click_s()
        time.sleep(2)
        find_agent.enter_city()
        time.sleep(2)
        find_agent.confirm_city()
        time.sleep(2)
        find_agent.enter_locality()
        time.sleep(2)
        find_agent.confirm_locality()
        time.sleep(2)
        find_agent.get_alert()
        time.sleep(2)
        find_agent.accept_t_and_c()
        time.sleep(2)
        find_agent.post_req()
        time.sleep(5)
